### ISSUE TITLE
Issues with @blocknotes & next

### ISSUE THREAD

**Issue by Nostromos** [adityaphasu/notion-clone#2]
When you upgraded blocknotes up to 14, did you have any issues with it? I'm getting typeerrors trying to render and your repo is the only one I found that seems to work.

**Comment by adityaphasu** [comment]
hey @Nostromos! 
Apart from blocknote deprecating `useBlockNote` hook and adding one more dependency `@blocknote/mantine` to render the `<BlockNoteView>` I didn't seem to face any type issues when upgrading. Could you elaborate more on what kind of type errors are you getting ?

**Comment by Nostromos** [comment]
I was getting the same error seen here: https://github.com/TypeCellOS/BlockNote/issues/1083

I downgraded to the version you were using and had the same issue. Oh well! They just pushed a fix that I think will fix it.
